### ISSUE TITLE
Exporting tilemap

### ISSUE THREAD

**Issue by tomaz** [infromthecold/Next-Graphics#1]
Heya!

Does this tool also support exporting tilemap (the layout of the screen)?

Maybe I'm missing the obvious and I only tried exporting as asm file. As far as I can see, it correctly exports colours and tile definitions, but not the screen itself.

I think the last part of the exported file is supposed to be X,Y pairs of each tile on the screen (which would make sense as there are 36 of them), but all coordinates are 0,0. I'd also expect that width/height would match the setup from the bitmap (40x32) but it's 1x1:

```
level1TileWidth:	equ	1
level1TileHeight:	equ	1
level1Block0:		.db	0,0
level1Block1:		.db	0,0
...
level1Block35:		.db	0,0
```

Is this intended result or a bug? I'm going through the code at the moment, maybe it will make more sense afterwards...

**Comment by tomaz** [comment]
Ohh, running the project from source code works better (used precompiled binary from your website before). The coordinates for each tile map into the tile definition X,Y, but width/height is still 1x1 and there is no export of the screen coordinates for the tiles.

With this in mind, I'd propose a change: when exporting tilemap, each block should include 3 bytes:
- index of the tile definition (this should be enough, since definitions are exported as flat list)
- X coordinate of the **screen**
- Y coordinate of the screen

Additionally, tilesmap export would be "embedded" within 2 labels: `<name>Tilemap` at the tope and and  `<name>TilemapSize equ $-<name>Tilemap` at the bottom, so it would be simple to iterate over the list. Maybe third label that would mark the end of the tilemap, not the size in bytes too - sometimes it's easier to iterate comparing current address not using a counter...

It will probably need to work differently when exporting sprites - didn't try that yet.

Don't want to get over my head, but should I prepare this as a pull request, would it interest you to include it to your repo?

**Comment by tomaz** [comment]
Gotcha, after spending more time with code (and enabling full comments which were disabled for some reason), previously misinterpreted byte (to put it midly) turns out to be attributes 🙈 Still X,Y for position on tilemap is not there

**Comment by infromthecold** [comment]
I have a new version for you with some fixes, I compile it every time I want to use it. That way I can make changes as I need them, it's always a work in progress :)  Its tooling to create the game art in a format i need, i use the asm files in my code with binary data, so that's the binary+ option, there are a few added features since the git update!

I have updated Git with the latest version!

**Comment by tomaz** [comment]
Great, pulling changes right away!

In the meantime I started working on the code - I'd first like to make export code easier to deal with. At the moment it's full of ifs/elses so it's hard to see what's going on. My idea is to convert single function into class hiearhcy, each export type its own class, driven from a single place.

Though I made it a kind of a rabbit hole: in order to do so, I need data extracted out of the views (which is a good idea regardless - among other benefits it opens up possiblity to run this tool from command line for example which can then be used in automated exports). I'm done with this part (including unit tests for loading and saving to make sure I didn't mess something up). Next comes replacing data in views with the one I extracted and then actual export, again with unit tests first so all existing functionality is preserved. A "bit" of a short term pain, but hopefully for a long term gain...

**Comment by infromthecold** [comment]
Yeah the if else's were to try and cater for everyone but it got messy as you say, so i ended up only supporting the asm/bin+ option as that's all I needed. The tool does the job for me, as i render my art, then photoshop into a uniform spritesheet (with tidying the sprites and making all the flips correct) then chuck it through this, as you see it outputs a ASM file for sprites that contains the palettes, collisions data, and the 16x16 sprite data, along with a bin file for loading the actual data. Or tile map, with blocks and tiles, in binary formats.  There is a debug window in the latest version, which may help you. Also there is a batch mode on the menu that processes a group of xml files, did you see it? Oh and have a look at the tiles export there is a map exported.

It would be nice if it did other formats like c64 fat pixel etc or Amiga as those machines are getting a new lease of life, but I don't have the time would you like to be added as a contributor ?

**Comment by tomaz** [comment]
I know how it goes when you just want to get some results and that's fine. My current changes will "just" make the code more maintanable without really adding anything. Which is also nice to have - you put the effort into creating the tool in the first place, so I'm more than happy to put my effort into improving it!

Didn't check most of mentioned options yet... Sounds like it does everything I'd need, so will definitely experiement.

You can add me as contributor, sure!

**Comment by tomaz** [comment]
And prepared PR 🎉, let me know if there's anything needing further change, or I missed something etc... https://github.com/infromthecold/Next-Graphics/pull/2

**Comment by infromthecold** [comment]
Many thanks, this game I'm making for the Next, is my last game,  so the
tools will be left unmaintained when my game is finished. At that point I
will also be releasing the parallax creator that plugs into next graphics.

**Comment by tomaz** [comment]
Aww, that feels a strong statement in a way... At this point I still don't see myself getting away from programming - it satisfies my creative mind...

Arrived to your tool from making Next game (albeit very simple one due to time constraints). What I need is support for 9-bit palette and export of tilemap data (unless this is what your parallax tool does?). As bonus make asm export templateable and the tool cmd line friendly (to hook up directly to ProMotion NG export for example). But to implement this in a controlled way, I first wanted to extract data (done with my PR) and export code (coming after first PR is merged).

**Comment by infromthecold** [comment]
The parallax tool, creates a series of tiles, or-ing them over a parallax image, I would release it now, but then my game would have less impact as everyone will be parallax-ing everything.  The reason I am giving up coding is because I have been doing it 39 years, and at 63 i think its time I got up from my chair and did something more active. Its a shame as the Next is a fantastic machine and I could do some great stuff for it, so instead I am publishing my tooling, and maybe write a book explaining my game code and tools that will come with the book,  making it like an engine that others can just use all or parts of my code and tooling.

**Comment by tomaz** [comment]
Sounds exciting! I still have 15 years to "catch" you, and by that time may have enough as well 😅 A book would be a nice project - I enjoyed working on mine, I thought I'd get bored but surprisingly not even for a moment. Anyway, you have 1 reader here already if you go for it 🤓

**Comment by tomaz** [comment]
Heads up: been consumed with my job in the past weeks, but managed to slowly iterate here too... So far moved slicing code from `Main.cs` to separate class which was the last "barrier" before tackling export code itself. It's all based on top of my existing pull request but if you aprove that in the meantime, it can still get merged independently (ideally, to avoid your own additions from departing too much). Otherwise I'll add export on top of that same PR. Hopefully I should have more time till the end of the year...

**Comment by tomaz** [comment]
Was able to finish extracting export code. There are still opportunities for improving, but that can easily turn into infinite task (probably assembler exporter will get further treatment when/if templates are introduced). As is now, works on my samples. You probably have much more complex projects, so definitely let me know if anything is amiss...

I was extra careful with callbacks to parallax window. It should work, but couldn't verify so it's possible some tweaks are needed... If so, should be straighforward, and if you don't want to deal with it, let me know of concrete issues and I can deal with them, or at minimum prepare additional hooks.

About code style: I use standard C# style, whenever I copy/paste code, it gets restyled so it looks quite different from the style you use. I can restyle back closer to what you use if you dislike it... Also let me know of any other areas you'd like changed - I'm quite used to code reviews where PR goes back and forth until common ground is reached...

Red colour is missing on info window, not sure why, the code looks ok, still looking into it...

https://github.com/infromthecold/Next-Graphics/pull/3
